### ISSUE TITLE
Udemy Account Opening up 

### ISSUE THREAD

**Issue by ashwaryahPisces** [Sahil-Ajmera/CalcApp#11]
CHECK FOR FRIENDS UDEMY ACCOUNT OPENING INFORMATION FOR CODING ON PYTHON

**Comment by Sahil-Ajmera** [comment]
You do not need friends account. You can sign up for a 30 day money back subscription for the course which is present in the link. Just remember to unsubscribe before 30 days.  I have tried it in the past so you would not be charged.

**Comment by Sahil-Ajmera** [comment]
You do not need this anymore
