### ISSUE TITLE
VODAFONE INTERNET SERVER RESOLVE 

### ISSUE THREAD

**Issue by ashwaryahPisces** [Sahil-Ajmera/CalcApp#7]
VODAFONE SERVER IS BEING FIXED FOR NET CONNECTIONS @ ASHWARYAH SIDE

**Comment by Sahil-Ajmera** [comment]
Comment here once the issue is fixed and click on 'Comment'

By using @ you can reach me and once you do that I get a notification from anywhere.

**Comment by ashwaryahPisces** [comment]
done and resolved
